stages:
  - build
  - deploy

variables:
  JAR_NAME: "jaunts-1.0.0.jar"
  APP_NAME: "jaunts"
  SERVER_HOST: "192.168.64.2"
  SSH_PASSWORD: "365278941"

# Local'de JAR build et
build_jar:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  before_script:
    - java -version
    - mvn --version
  script:
    - echo "Building JAR file locally..."
    - mvn clean package -DskipTests
    - cp target/$JAR_NAME ./$JAR_NAME
    - ls -la $JAR_NAME
  artifacts:
    paths:
      - $JAR_NAME
    expire_in: 1 hour
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu

# Sunucuda Docker ile deploy
deploy_docker:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync sshpass
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "sudo apt update && sudo apt install docker-compose-plugin -y"
  script:
    - echo "Deploying to server with Docker..."
    - sshpass -p "$SSH_PASSWORD" rsync -avz $JAR_NAME gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz docker-compose.yml gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz Dockerfile gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz nginx.conf gitlab-runner@$SERVER_HOST:/opt/jaunts/nginx/ || true
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose down || true"
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose up --build -d"
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose ps"
  dependencies:
    - build_jar
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu
