stages:
  - build
  - deploy

variables:
  JAR_NAME: "jaunts-1.0.0.jar"
  APP_NAME: "jaunts"
  SERVER_HOST: "192.168.64.2"
  DOCKER_BUILDKIT: "1"

build_jar:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  before_script:
    - java -version
    - mvn --version
  script:
    - echo "Building JAR file locally..."
    - mvn clean package -DskipTests -T 1C  # Paralel build
    - cp target/$JAR_NAME ./$JAR_NAME
    - ls -la $JAR_NAME
  artifacts:
    paths:
      - $JAR_NAME
    expire_in: 1 hour
  cache: # Maven cache ekleyelim
    paths:
      - .m2/repository
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu

deploy_docker:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync sshpass docker
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Deploying with rolling deployment strategy..."

    # Dosyaları transfer et
    - sshpass -p "$SSH_PASSWORD" rsync -avz $JAR_NAME gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz docker-compose.yml gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz Dockerfile gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - sshpass -p "$SSH_PASSWORD" rsync -avz nginx.conf gitlab-runner@$SERVER_HOST:/opt/jaunts/nginx/ || true

    # Yeni image'ı build et
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && DOCKER_BUILDKIT=1 docker-compose build jaunts"

    # Nginx'i önce başlat (eğer çalışmıyorsa)
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose up -d nginx || true"

    # Eski jaunts container'ını durdur
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose stop jaunts || true"

    # Yeni jaunts container'ını başlat
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose up -d jaunts"

    # Health check - 60 saniye bekle
    - echo "Waiting for application to be healthy..."
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "
      cd /opt/jaunts &&
      for i in \$(seq 1 12); do
      if docker-compose exec -T jaunts curl -f http://localhost:8080/actuator/health >/dev/null 2>&1; then
      echo 'Application is healthy!';
      break;
      fi;
      echo \"Health check attempt \$i/12 failed, waiting 5 seconds...\";
      sleep 5;
      done
      "

    # Container durumlarını göster
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose ps"

    # Eski unused image'ları temizle
    - sshpass -p "$SSH_PASSWORD" ssh gitlab-runner@$SERVER_HOST "docker image prune -f || true"

  dependencies:
    - build_jar
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu
