stages:
  - build
  - deploy

variables:
  JAR_NAME: "jaunts-1.0.0.jar"
  APP_NAME: "jaunts"
  SERVER_HOST: "192.168.64.2"

# Local'de JAR build et
build_jar:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  before_script:
    - java -version  # Log JDK version
    - mvn --version  # Log Maven version
  script:
    - echo "Building JAR file locally..."
    - mvn clean package -DskipTests
    - cp target/$JAR_NAME ./$JAR_NAME
    - ls -la $JAR_NAME
  artifacts:
    paths:
      - $JAR_NAME
    expire_in: 1 hour
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu

# Sunucuda Docker ile deploy
deploy_docker:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync sshpass
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to server with Docker..."
    # Dosyaları sunucuya kopyala
    - rsync -avz $JAR_NAME gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - rsync -avz docker-compose.yml gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - rsync -avz Dockerfile gitlab-runner@$SERVER_HOST:/opt/jaunts/
    - rsync -avz nginx/nginx.conf gitlab-runner@$SERVER_HOST:/opt/jaunts/nginx/ || true
    # Deploy et
    - ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose down || true"
    - ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose up --build -d"
    - ssh gitlab-runner@$SERVER_HOST "cd /opt/jaunts && docker-compose ps"
  dependencies:
    - build_jar
  only:
    - main
  tags:
    - jaunts
    - docker
    - ubuntu
