services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: jaunts-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8080
      - TZ=Europe/Istanbul
    volumes:
      - app-logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - myapp
    networks:
      - app-network

volumes:
  app-logs:
  nginx-logs:

networks:
  app-network:
    driver: bridge
