services:
  jaunts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaunts-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - TZ=Europe/Istanbul
      # JVM başlangıç optimizasyonları
      - JAVA_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s  # 60s'den 30s'e düşürdük
    # Resource limits ekleyelim
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on'u kaldırıyoruz, paralel başlasın
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
