package com.travelapp.helper.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION, PAYMENT_SUCCESS, PAYMENT_FAILED, TOUR_REMINDER,
    CANCELLATION, REFUND, REVIEW_REQUEST, PROMOTIONAL, SYSTEM_MAINTENANCE
}
